# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.6.3

pipelines:
  default:
    - step:
        caches:
          - bundler
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get clean
          - apt-get update 
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py --user
          - pip3 --version
          - pip3 install awscli --upgrade --user
          - bundle install --path vendor/bundle
          - bundle exec rake
          - aws --version
          - eb init My-Application -r us-west-2 -p arn:aws:elasticbeanstalk:us-west-2::platform/Puma with Ruby 2.6 running on 64bit Amazon Linux/2.11.0
          - eb deploy MyApplication-production
        services:
          - mysql
definitions:
  caches:
    bundler: vendor/bundle
    pip: ~/.cache/pip
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: 'myapp_test'
        MYSQL_USER: 'root'
        MYSQL_ROOT_PASSWORD: '\0'
