# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.5.3

pipelines:
  default:
    - step:
        caches:
          - bundler
          - pip
        script: # Modify the commands below to build your repository.
          - bundle install
        services:
          - mysql
definitions:
  caches:
    bundler: vendor/bundle
    pip: ~/.cache/pip
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: 'myapp_test'
        MYSQL_USER: 'root'
        MYSQL_ROOT_PASSWORD: '\0'
